### ISSUE TITLE
enhance go-log's ability

### ISSUE THREAD

**Issue by printfcoder** [micro/development#1]
We all know go-log is just extended from log of golang native lib at present.
go-log should support saving logs to file, mq, kafka, etc.

Of course people can do this by other plugins or libs. Why we make people do that?

I think go-log should has a more easy way to integrate those, and so is usage. We can let people do nothing, except import it.

Emm, just thinking it should be out-of-box with common and typical usages.

**Comment by xmlking** [comment]
I think following capabilities are expected for  typical logging  Usecase 
1. Log formatter  - text, json
2. Log level - info, debug , error ....
3. WithFields - to add context data


Experimenting here 
https://github.com/xmlking/micro-starter-kit/blob/master/shared/log/log.go

**Comment by asim** [comment]
I think we have solved this problem with the new go-micro/logger
