### ISSUE TITLE
Service to Service Namespace

### ISSUE THREAD

**Issue by asim** [micro/development#100]
Currently this https://github.com/micro/go-micro/blob/master/util/wrapper/wrapper.go#L178 logs when there's no namespace but its not actually being set anywhere in a service to service call or within the service itself. I can see code has been added to insert this in the API code but we have multiple entrypoints and service to service calls are a first class citizen. We cannot ever assume that a request is just by a user. We should ensure every service sets the Namespace any other relevant values.

Headers which a service has to propagate should be included in the metadata wrapper.

**Comment by ben-toogood** [comment]
In-keeping with abstracting namespace logic to micro, this is no longer needed in go-micro.
