### ISSUE TITLE
Document Multi-Tenancy / Namespacing

### ISSUE THREAD

**Issue by asim** [micro/development#111]
Document how we expect multi-tenancy / namespacing to work across the platform. This goes beyond auth and should highlight how we expect each core runtime service to deal with namespacing and multiple tenants. It should include any design or architecture related information so that if any new services are creating we can develop it in a known way e.g auth.NamespaceKey, wrappers, account from context, store prefixing, table names. 

I should be able to read this doc and create a new core service inline with design. 

Add to design/multi-tenancy.md https://github.com/micro/development/blob/master/design/multi-tenancy.md

**Comment by ben-toogood** [comment]
@asim please see: https://github.com/micro/development/blob/master/design/multi-tenancy.md
