### ISSUE TITLE
Fix intermitted onboarding bug

### ISSUE THREAD

**Issue by ben-toogood** [micro/development#116]
Standard (non-admin) accounts are periodically being shown the onboarding flow when they loaded up the account web app.

**Comment by ben-toogood** [comment]
@asim this appears to have been an issue with the timeout from Stripe. I increased the timeout from 500ms to 1s and this appears to have fixed the issue. Please lmk if you experience it again and I can look into adding a cache.

**Comment by asim** [comment]
Thanks that looks to have fixed it
