### ISSUE TITLE
Rewrite micro/actions in Go

### ISSUE THREAD

**Issue by asim** [micro/development#122]
The majority of what we do should be written in Go. Github actions supports running a docker container which means we can rewrite the action in Go. https://help.github.com/en/actions/building-actions/about-actions

- [x] Rewrite micro/actions to be a Go program in docker
- [x] Ensure its reusable across any repo so we can give to users
- [ ] Switch out the existing action modified files check in our build

**Comment by crufter** [comment]
The current Github action uses the action context to get the commit diff.
This can be easily done by calling the Github API.

This would have the advantage of working for fork PRs too as Github actions do not have the privileges to see the diff in that case.

**Comment by asim** [comment]
Have a look at the github actions doc. It indicates whats passed in to the docker container. So the context might be available to the container. 

I mostly don't care about forks. Operate under the assumption that container is using the github token provided to the action.

**Comment by asim** [comment]
Rewritten by Ben
