### ISSUE TITLE
Micro web terminal

### ISSUE THREAD

**Issue by asim** [micro/development#142]
Add Terminal in micro web, much like what used to exist in the past. Go back 12 months in micro commit history to see what it was. Based on jquery terminal. Ideally we use maybe hyper.js? Or maybe we just ad-hoc create a repl.

**Comment by vtolstov** [comment]
i'm use xterm.js its fast, have typescript typings and actively maintained by microsoft to their vscode.
I'm use it via websocket over go-micro/api handler

**Comment by asim** [comment]
Interesting. Thats pretty cool. I think I'd like to bake this into the UI and make it use the built in web client to query internally.

**Comment by asim** [comment]
Closing to avoid distractions. Lets come back to this.
