### ISSUE TITLE
Clean up of m3o vs micro/services

### ISSUE THREAD

**Issue by domwong** [micro/development#150]
Let's get the repos clean as they are currently a mixture of things

**Comment by asim** [comment]
I have removed as much as possible from micro/services. The assumption is these are high level value add services on the platform e.g sms, email, payments or those used to run the platform itself. 

Android initially had everything in the OS for Google services then pulled them back out so they could benefit from the same update procedures as all other apps. Trying to minimize what's in micro/micro for the core runtime vs the additional services probably makes sense e.g payments probably not core.
