### ISSUE TITLE
Tutorial / getting started guide

### ISSUE THREAD

**Issue by domwong** [micro/development#164]
Construct a tutorial that helps new users construct an example project. Should probably end up with a project that has the following:

- Multiple micro services that call each
- HTTP API interface
- Storage
- Auth
- Async
- Config
- Errors (fix error story too)

**Comment by crufter** [comment]
So the state of this: we have a getting started and a blog building tutor post 1 but the set of features covered is different than this. So I think we can put this back to todo as it's not overly important right now (pre MVP).
