### ISSUE TITLE
nil registry error (mdns)

### ISSUE THREAD

**Issue by ben-toogood** [micro/development#165]
I'm getting a nil host error intermittently locally:
```
2020-05-25 12:50:54.293680 I | http: proxy error: dial tcp: lookup <nil>: no such host
```

However the service is registered okay:
```
micro@Bens-MBP-2 micro % micro get service go.micro.web.auth 
service  go.micro.web.auth
version latest
ID	Address	Metadata
c4733ac4-6bf8-4e3e-8c24-0ad66eef9199	[fdaa:bbcc:ddee:0:8da:d8d7:aa4c:6792]:59716	
```

micro web is configured to use mdns.

**Comment by domwong** [comment]
Also similar issues here https://github.com/micro/micro/issues/392

**Comment by domwong** [comment]
https://github.com/micro/go-micro/pull/1660

**Comment by domwong** [comment]
Should be fixed in master of go-micro now
