### ISSUE TITLE
API gateway rpc interface

### ISSUE THREAD

**Issue by asim** [micro/development#17]
Add rpc interface for all gateway outbound request via http

**Comment by crazybber** [comment]
does this mean api-gateway receive http requet and forward calling as rpc/grpc to internal services ?

**Comment by asim** [comment]
The egress will be done soon but non priority

**Comment by vtolstov** [comment]
@crazybber you can do that with api rpc handler and static api router

**Comment by crazybber** [comment]
> @crazybber you can do that with api rpc handler and static api router

i got it,thx.
