### ISSUE TITLE
Micro server gives no feedback when a service doesn't compile

### ISSUE THREAD

**Issue by crufter** [micro/development#188]
Says `Processing update event` but then if the service fails to build it's only visible from its log.

I think it would be nice to see a oneliner error in the `micro server` output.

**Comment by domwong** [comment]
I think this should now be successfully reflected in the `micro status` command with this fix. https://github.com/micro/micro/pull/922

```
$ micro status
NAME		VERSION	SOURCE			STATUS		BUILD	UPDATED	METADATA
helloworld	latest	helloworld.tar.gz	exit status 2	n/a	unknown	owner=n/a,group=n/a

```

But we can definitely add a line in the server logs too.

**Comment by domwong** [comment]
Added a log line to https://github.com/micro/go-micro/pull/1686/files

**Comment by domwong** [comment]
Fixed with log line in https://github.com/micro/go-micro/pull/1686/files
