### ISSUE TITLE
Can micro.RegisterSubscriber() support setup broker.SubscribeOption()?

### ISSUE THREAD

**Issue by Funnyang** [micro/development#19]
For example, I want to use `rabbitmq.DurableQueue()`, I must use `broker.Subscribe()`. Actually, I perfer to use `micro.RegisterSubscriber()`.

**Comment by Funnyang** [comment]
I find another way, like this:

```
bo := broker.NewSubscribeOptions(rabbitmq.DurableQueue())

micro.RegisterSubscriber("example.topic.pubsub.2", service.Server(), subEv, server.SubscriberQueue("queue.pubsub"), server.SubscriberContext(bo.Context))
```

Nice!

**Comment by asim** [comment]
Looks like you've figured it out

**Comment by asim** [comment]
I believe we have passthrough capability now
