### ISSUE TITLE
micro update does not clean old nodes from the registry

### ISSUE THREAD

**Issue by crufter** [micro/development#199]
Repro: do multiple `micro update .` and check `micro get service [servicename]`
The node section will look something like this:

```
go.micro.service.post-866c31b0-b716-4876-b0b7-7f9677ae9695	192.168.43.193:33595	broker=service,protocol=grpc,registry=service,server=grpc,transport=grpc
go.micro.service.post-eabf9505-f191-4323-9ed6-a47e6b77b1c1	192.168.43.193:44697	transport=grpc,broker=service,protocol=grpc,registry=service,server=grpc
go.micro.service.post-d8bbd519-b4e5-43f1-946d-6a3d4e6f47e4	192.168.43.193:46047	broker=service,protocol=grpc,registry=service,server=grpc,transport=grpc
```

**Comment by asim** [comment]
The runtime/local/process package makes use of SIGKILL https://github.com/micro/go-micro/blob/master/runtime/local/process/os/os.go#L71. Go programs cannot catch SIGKILL https://golang.org/pkg/os/signal/#hdr-Types_of_signals and so we must switch to SIGINT or SIGTERM.

**Comment by asim** [comment]
We only retry once by default. Ideally we should potentially change retry logic to continuously retry until context timeout rather than the number of retries. The timeout is bounded to that particular call and in the call stack timeout is shaved down so that every service only uses the amount of time its allocated

**Comment by ben-toogood** [comment]
What do we retry once by default?

**Comment by asim** [comment]
We retry 408 and 500s. RetryOnError is the default function used https://github.com/micro/go-micro/blob/master/client/retry.go#L18.Its an option that can be passed in.

**Comment by domwong** [comment]
https://github.com/micro/go-micro/pull/1687
