### ISSUE TITLE
micro login for new users

### ISSUE THREAD

**Issue by domwong** [micro/development#228]
add `--new` which will create a new account. e.g. something like

```
$ micro login  foo bar
{"id":"go.micro.auth","code":400,"detail":"Account not found with this ID","status":"Bad Request"}
$ micro login --new foo bar
Success!
```

**Comment by domwong** [comment]
See latest thinking https://github.com/micro/development/pull/223

**Comment by crufter** [comment]
I think the current plan is implementing this with emails https://github.com/micro/development/pull/223
