### ISSUE TITLE
gRPC transport, integration and interop

### ISSUE THREAD

**Issue by asim** [micro/development#23]
See https://github.com/micro/development/blob/master/grpc.md

Discussion here and editing of doc in PR.

**Comment by yarbelk** [comment]
Pure comment: the gRPC semantics of micro are part of its draw for me. and why i've used it in 3 companies at this point.

**Comment by asim** [comment]
Interesting. That's great to hear. Can you elaborate on what works well and what could do with improving?

**Comment by asim** [comment]
We've moved to grpc by default
