### ISSUE TITLE
Git operations are not thread safe in go-micro

### ISSUE THREAD

**Issue by crufter** [micro/development#237]
See `runtime/local/git/git.go`, locking or using different folders for each service (wasteful) should fix this.

**Comment by domwong** [comment]
@crufter interesting. It checks it out to `$TMPDIR/<full-url-with-dashes-not-slashes>` so even if you make the `Gitter` struct thread safe in terms of the struct's fields you still could have problems with two different `Gitter`s trying to create two different versions of the same service. 

So not something we can solve with just a simple lock it seems. I think the simplest solution might be to add an extra random string to the directory name

**Comment by crufter** [comment]
@dom that would definitely be the safest and cleanest way, with some sparse checkout (or whatever that feature is called) we could probably reduce the amount of things downloaded.
