### ISSUE TITLE
Revive api.m3o.com and web.m3o.com

### ISSUE THREAD

**Issue by asim** [micro/development#250]
There's been a lot of debate about how/where the api and web dashboards should be. I'm no longer welcoming debates about this. Micro inclusively includes entrypoints for every type of "client" including http/json and browsers. The api and web clients need to run at api.m3o.com and web.m3o.com respectively as they were doing for the past 12 months. Custom domains is currently a non-concern as anything with an api token will dictate what namespace the requests should flow into.

- {api, web, proxy}.m3o.com - http/json, browser and gRPC

<img src="https://m3o.com/images/runtime.svg" />

**Comment by domwong** [comment]
@asim sounds like this isn't needed anymore ?

**Comment by asim** [comment]
Yea you're right. We go the route of no api or web UI until we decide its needed.
