### ISSUE TITLE
Move signup to its own command

### ISSUE THREAD

**Issue by asim** [micro/development#279]
We have conflated signup and login as one command baked into the OSS, this is causing some issues but also highlights that signup comes before login, not during. By doing this separately we can effectively have `micro signup` for the product and as a service, rather than baking it into login. Eventually turning it into a dynamic CLI command only available on the platform or in staging. Users running locally or in their own environments can use `micro auth create account` as the pure OSS experience.

Eventually we may get around to some sort of single sign on like model that does not require this step but for now `micro login` should just be email/pass and `micro signup` deals with an OTP for email verification.

- `micro signup` - signup to the platform, verify email via OTP (dynamic CLI command in future)
- `micro login` - sign in to any micro server using username/password (username is email)

**Comment by crufter** [comment]
Done.

**Comment by asim** [comment]
💥
