### ISSUE TITLE
Error Reporting: Email support@m3o.com anytime there is a CLI issue for the platform

### ISSUE THREAD

**Issue by asim** [micro/development#286]
We need to track errors and usage problems related to micro and the platform. We have a 10 or so command workflow, from signup to accessing your service. If anything fails, not only do we need to know about it but we also need to let the user know where they can come find us.

We should (when env is set to "platform")

1. Indicate "Please go to #support channel on Slack at https://slack.m3o.com for help if the issue persists"
2. Email the exact error report to support@m3o.com so we get an email and can keep track of problems

**Comment by crufter** [comment]
Done in a different with (with Google Analytics) in https://github.com/micro/micro/pull/1103
Currently only reports login and signup but we can add more on demand.
