### ISSUE TITLE
Transport: http bidirectional streaming

### ISSUE THREAD

**Issue by asim** [micro/development#32]
The HTTP transport suffers from a quirk which requires the client to send a request before the server can stream a response. The server is unable to push responses as and when it requires. This is due to a limitation with http itself.

There are implementations of BOSH for bidirectional streaming on http https://en.wikipedia.org/wiki/BOSH_(protocol) which solves this problem by having the client send a request and them immediately a second one, the server then has the option of sending a response, the client also opens a second stream to send more requests if it needs. This is potentially one solution. There may be others.

We may be better off moving to h2c as the default and falling back to http/1.1 when we need.

**Comment by zfsamzfsam** [comment]
https://github.com/twitchtv/twirp/pull/112

Proposal: Support streaming in the Twirp spec 
https://github.com/twitchtv/twirp/issues/3
Proposal: Go streaming API
https://github.com/twitchtv/twirp/issues/70

**Comment by asim** [comment]
We did unlocking of streams in the rpc streaming code which partially fixes this issue but also moved to grpc by default
