### ISSUE TITLE
Toolkit: dynamic plugins

### ISSUE THREAD

**Issue by asim** [micro/development#33]
Micro plugins currently require rebuilding of the toolkit. We should be able to support plugins without rebuilding.

There are three paths for this.

1. Require rebuilding - use of micro/plugin package and calling plugin.Register
2. Dynamic loading - use the golang plugin interface to create DSOs 
3. RPC interface - provide an rpc interface that loads modules much like hashicorp/go-plugins

**Comment by vtolstov** [comment]
i'm prefer rpc interface for plugins:
* we don't need to rebuild all or build from identical sources
* to not expose tcp ports we can use shm (something like https://github.com/hidez8891/shm) as plugins run on the same machine
* we can prebuild plugins for common arches and pull from github

**Comment by asim** [comment]
I think there are a couple things that will work here.

1. Docker images should just build on the fly when running and if plugins are included it will work
2. We should prebuild the plugins on release using github actions. Since github supports binary data as part of releases this will work
3. We should investigate the shared memory approach which might be a better way than anything else
4. RPC might be slower than what we want

**Comment by vtolstov** [comment]
mostly i think about rpc via shm transport =)
