### ISSUE TITLE
Account Page: Roles in a separate location?

### ISSUE THREAD

**Issue by asim** [micro/development#54]
![Screenshot 2020-03-19 at 11 32 54](https://user-images.githubusercontent.com/17530/77063648-f7872080-69d5-11ea-8fe8-473aa72b732d.png)

Should roles be displayed to the user here? Can they be displayed in settings menu or a separate tab?

**Comment by ben-toogood** [comment]
It was mainly for debugging purposes, i'll remove this now it's working

**Comment by ben-toogood** [comment]
Completed: https://github.com/micro/services/pull/96
