### ISSUE TITLE
Login Redirect

### ISSUE THREAD

**Issue by asim** [micro/development#56]
Once logged in the user is left on the /account page. We should redirect to wherever the user came from aka the referer. This will mean regardless of hitting / or /home or /platform you will always end up back where you expected to be.

**Comment by ben-toogood** [comment]
https://github.com/micro/services/pull/112

**Comment by ben-toogood** [comment]
This is now working, account web redirects to whatever the redirect_to url param is, and this works for the oauth flow as well.
