### ISSUE TITLE
GitHub/Google Login position

### ISSUE THREAD

**Issue by asim** [micro/development#57]
It would be good to move github and google login buttons to be below the micro signup on the login page so the buttons are all near each other and we prioritise our own signup.

**Comment by ben-toogood** [comment]
I'm not sure I agree with this whilst we're still allocating roles based on oauth credentials. If a user logs in using their email & password, they gain access but have 0 privelages.

**Comment by asim** [comment]
Does it make sense to just give everyone who signs up a developer role considering we're a developer product?

**Comment by ben-toogood** [comment]
That makes sense, as part of the new onboarding flow i'm forcing users to complete their profiles, so oauth or email / password really makes no difference.
