### ISSUE TITLE
optimize handlers usage

### ISSUE THREAD

**Issue by printfcoder** [micro/development#7]
We now support service using handler by passing flag `--handler=***`. 

How about if people just import those handlers as plugins, then service will using this handler?

eg.
plugins.go
```golang
import _ "github.com/micro/go-api/handler/broker"
```
run

```
$ go run main.go plugins.go
# which equals to
$ go run main.go --handler=broker
```

**Comment by asim** [comment]
Should be done but closng as this issue is stale.
