### ISSUE TITLE
Multi-tenancy: Namespacing in Micro

### ISSUE THREAD

**Issue by asim** [micro/development#71]
We need to incorporate namespacing into Micro itself so that we can do multi-tenancy

- Accounts are tied to a namespace - if nothing is defined its part of the default namespace
- Namespace is passed in the header Micro-Namepace
- Namespace is also within the token used to verify against the header thats used
- HTTP and service wrappers inject namespace as headers

Identity
- Service identity is verified by Auth service against the runtime based on service name
- User identity is verified by Auth service against oauth2 providers
- Scope account tokens to a specific namespace

Registry
- Filter namespace based on token. Use prefix in the names.

Store
- Namespace is the database
- Table is the service name

Broker (???)
- Filter topics based on namespace?

Runtime (Asim)
- Add namespace as prefix on name
- Add namespace as label

**Comment by crazybber** [comment]
I think we should distinguish and define  tenancy and namespace more clearly .
kubernetes also has its namespace.If devops put these concepts together,they may get confused.

**Comment by asim** [comment]
I agree with your point @crazybber. We need more clarity around this. Our namespacing is not k8s namespacing. We had namespacing as part of service names to distinguish between different tenants and types of services and now we're building in this multi-tenancy.

Namespace: stripe
Type: api, web, service
Alias: helloworld
String(): stripe.api.helloworld

We have always supported dotted names and reversed a domain but may strip that away

**Comment by asim** [comment]
I think we're basically done.
