### ISSUE TITLE
micro login

### ISSUE THREAD

**Issue by asim** [micro/development#77]
Make micro login prompt for id and secret

- If user specifies `micro login --token` accept that login
- Otherwise `micro login` should prompt for id and secret
- Id and Secret should be stored in the local config

**Comment by ben-toogood** [comment]
@asim what is ID needed for? Current Refresh method only required secret so ID is redundant. We can change interface so both ID and secret are required to issue a new JWT

**Comment by asim** [comment]
I think it makes sense to pass through id/secret. Anywhere I'm looking at oauth flow it appears its always both because you can't really infer from the secret what account its for. I'd also assume `micro login` is a user driven thing and should require id/secret.

**Comment by ben-toogood** [comment]
So update `Refresh(secret string) (*auth.Token, error)` to `Refresh(id, secret string) (*auth.Token, error)`?

**Comment by asim** [comment]
Yea I think that makes sense. What do you think?

**Comment by asim** [comment]
I mean in that case Refresh sounds weird. Because you don't really refresh based on a secret. You Login or Authorize

**Comment by asim** [comment]
Refresh feels like a background function of the Token itself to replace one jwt with another

**Comment by ben-toogood** [comment]
I don't mind too much, I think the refresh name is weird. It makes sense to have an account ID and a secret. We could rename to "Token" and take id, secret as arguments. Since it's generating a token I think this makes sense.

**Comment by asim** [comment]
Yea lets do that!
