### ISSUE TITLE
Account Onboarding Tweaks

### ISSUE THREAD

**Issue by asim** [micro/development#81]
Going from micro.mu/pricing to being logged in at web.micro.mu:
- Pricing page micro.mu/pricing - Click "Signup" goes to /account/signup
- Signup page /account/signup goes through signup flow and redirects to account settings
- Settings page enables developer to specify a namespace and configure their account
- Developer can now click "Home" or Back and be redirected to web.micro.mu

Signup page should include:
- Community - free shared environment
- Developers - paid solo developer $35/month
- Teams - $45/user/month - Coming soon

Users with @micro.mu email address should skip signup and be logged in

**Comment by ben-toogood** [comment]
Users with @micro.mu email address should skip signup and be logged in: this has already been implemented if you log in with Google.

**Comment by ben-toogood** [comment]
Settings page enables developer to specify a namespace and configure their account: @asim do we need to allow users to see / set this? I was planning on setting it behind the scenes since it likely won't be the same as their service namespaces and it's easier to ensure namespaces don't conflict.

**Comment by ben-toogood** [comment]
@asim what repo would micro.mu/pricing exist in?

**Comment by asim** [comment]
> "Users with @micro.mu email address should skip signup and be logged in: this has already been implemented if you log in with Google."

This doesn't work if I signin with github or my email/pass. I think it should probably work regardless of which method we use. I was also getting "Invalid Email" over the weekend. Are accounts not being stored yet?

> what repo would micro.mu/pricing exist in?

The pricing page is a static html page in micro/website/pricing. We can probably redirect to https://account.micro.mu/signup, web.micro.mu/account/signup or internally proxy so we're just routing /signup to web.micro.mu/account/signup. 

> Settings page enables developer to specify a namespace and configure their account: @asim do we need to allow users to see / set this? I was planning on setting it behind the scenes since it likely won't be the same as their service namespaces and it's easier to ensure namespaces don't conflict.

Ok sounds like a good plan to start, I was conflating internal service namespacing with the overall one but you're right, these do not have to be the same.

**Comment by ben-toogood** [comment]
Done.
