### ISSUE TITLE
need API to support html|static dir

### ISSUE THREAD

**Issue by printfcoder** [micro/development#9]
both proxy and web handlers of api don't support serving static dir of go-web.

But, if api has a flag `--root=/path/to/html`, I think it is enough for using in most scenarios.

**Comment by asim** [comment]
Go Web now automatically serves a static dir as per this PR https://github.com/micro/go-web/pull/29. Does that solve the issue?

**Comment by printfcoder** [comment]
what i mean is if a go-web app runs behind api server and the api server should be able to serve the web app's static files.

eg.

go-web: mu.micro.demo.web.user

```
127.0.0.1:42233/index.html
```
then we can open the site through:
micro api: mu.micro.demo.web 
```
127.0.0.1:8080/user/index.html
```

**Comment by printfcoder** [comment]
```
service.Handle("/path", http.StripPrefix("/path", http.FileServer(http.Dir("html"))))
```
