### ISSUE TITLE
Invite-only

### ISSUE THREAD

**Issue by asim** [micro/development#94]
We want to continue to operate in an invite-only mode across the entire platform while we're in beta. This ensures we're providing a quality service and product. The need for onboarding doesn't go away. We need developers to understand how the platform works and how to leverage it for full effect, community, developer and team tiers.

Figure out what the most elegant invite only model is. Going through signup and needing to provide an invite token perhaps. (invite service?)

**Comment by ben-toogood** [comment]
Implementing now.
