### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by asim** [micro/development#96]
Send a verification email when a user creates an account. We need to ensure people are signing up with valid emails. This may also fall into the invite only issue where they must be provided an invite email.

- [ ] On signup set the account as "inactive"
- [ ] Send a verification email with a link that sets the account to "active"
- [ ] Kick through the flow if the account is "active" but otherwise wait

**Comment by ben-toogood** [comment]
I normally use sendgrid for this kind of thing. Are you cool with this?

https://sendgrid.com/pricing/

**Comment by asim** [comment]
We should just use our own email service and whitelist it with google?

**Comment by asim** [comment]
Actually sendgrid appears to be free for upto 100 emails/day. Lets start there!

**Comment by domwong** [comment]
Closing this issue as it's superseded by #228
